export * from './types.ts'
export { SchemaError, type SchemaErrorCode } from './errors.ts'
export {
  isTreeId,
  asTreeId,
  newComponentKey,
  newNodeKey,
  newSubpathId,
  newCommentId,
  isComponentKey,
  isNodeKey,
  isSubpathId,
  isOverridePath,
  isVirtualId,
  parseVirtualId,
  virtualId,
  isNodeRef,
  compareTreeIds,
} from './ids.ts'
export {
  FRACTIONAL_INDEX_JITTER,
  createEmptyDoc,
  loadDoc,
  exportSnapshot,
  transact,
  getDocName,
  setDocName,
  getSchemaVersion,
  nodesTree,
  metaMap,
  tokensMap,
  commentsMap,
  versionsMap,
  type CommitOptions,
  type CreateEmptyDocOptions,
} from './doc.ts'
export {
  createNode,
  moveNode,
  deleteNode,
  setStyle,
  setStyles,
  setText,
  setNodeProps,
  getNode,
  getNodeType,
  getParentId,
  getChildIds,
  hasNode,
  decodeNode,
  type CreateNodeInput,
  type CreateNodeOptions,
} from './nodes.ts'
export { setTokens, getTokens, isTokenName, type SetTokensOptions } from './tokens.ts'
export {
  MAX_COMMENT_LENGTH,
  MAX_COMMENT_MENTIONS,
  addCommentMessage,
  createCommentThread,
  decodeCommentThread,
  deleteCommentMessage,
  deleteCommentThread,
  editCommentMessage,
  getCommentThread,
  getCommentThreads,
  moveCommentThread,
  setCommentResolved,
  type CommentAuthor,
  type CommentMention,
  type CommentMessage,
  type CommentPin,
  type CommentThread,
} from './comments.ts'
export {
  MAX_AUTO_VERSIONS,
  MAX_VERSION_NAME,
  changedSinceVersion,
  createVersion,
  deleteVersion,
  docAtVersion,
  getVersion,
  getVersions,
  renameVersion,
  restoreVersion,
  type DocVersion,
  type VersionReason,
} from './versions.ts'
export { toSnapshot, toSubtreeSnapshot } from './snapshot.ts'
export {
  subscribeNodes,
  toNodeChangeBatch,
  type NodeChange,
  type NodeChangeKind,
  type NodeChangeBatch,
  type NodeChangeListener,
} from './events.ts'
export {
  generateBenchDoc,
  benchDocNodeCount,
  BENCH_MAIN_NODE_COUNT,
  type BenchDocOptions,
} from './bench.ts'
export {
  ACCEPTED_IMAGE_MIMES,
  ASSET_SCHEME,
  ASSET_URL_PREFIX,
  MAX_ASSET_BYTES,
  assetCssUrl,
  assetRefsInValue,
  assetUrlOf,
  collectAssetRefs,
  docAssetRefs,
  isAssetHash,
  mentionsAsset,
  nodeAssetRefs,
  rewriteAssetUrls,
} from './assets.ts'

// Phase 3 — canvas tools (docs/phase3/contract.md §4)
export {
  frameCenter,
  frameCorners,
  frameAabb,
  pointInFrame,
  rotatePoint,
  worldToLocal,
  localToWorld,
  unionRects,
  borderInsets,
  positionContextOf,
  placementStyles,
  docGeometry,
  type PositionContext,
} from './geometry.ts'
export {
  normalizeDeg,
  parseAngle,
  readRotation,
  rotationValue,
  rotateOnlyTransform,
  setRotation,
  rotateNodes,
} from './rotation.ts'
export { groupNodes, ungroupNodes, fitGroups, resizeGroup, wrapInFrame } from './groups.ts'
export {
  canReparent,
  reparentNodes,
  removeNodes,
  type ReparentMove,
  type ReparentTarget,
  type ReparentRefusal,
} from './reparent.ts'
export {
  listComponents,
  findMainComponent,
  isMainComponent,
  componentDependencies,
  wouldCreateCycle,
  wouldCreateCycleForKeys,
  createComponent,
  createInstance,
  detachInstance,
  restoreMainComponent,
  type ComponentInfo,
} from './components.ts'
export {
  setStylesAt,
  setTextAt,
  setPropsAt,
  resetOverrides,
  getOverrides,
  hasOverrides,
  type WriteAtOptions,
  type ResetOverridesOptions,
} from './overrides.ts'
export {
  createComponentResolver,
  toRenderSubtree,
  getResolvedNode,
  refExists,
  type InstanceStatus,
  type ResolvedNode,
  type ExpandedInstance,
  type AffectedByBatch,
  type ComponentResolver,
} from './resolve.ts'
export {
  vectorToPathD,
  formatPathNumber,
  vectorBounds,
  normalizeVector,
  scaleVector,
  splitSegment,
  nearestOnPath,
  setPointMode,
  resolveVars,
  vectorToSvgMarkup,
  setVector,
  editVector,
  setVectorGeometry,
  type VectorEdit,
} from './vector.ts'
export {
  CLIPBOARD_MIME,
  CLIPBOARD_KIND,
  CLIPBOARD_VERSION,
  MAX_CLIPBOARD_ASSET_BYTES,
  MAX_CLIPBOARD_NODES,
  serializeClipboard,
  attachAssetBytes,
  parseClipboardPayload,
  clipboardPayloadVersion,
  clipboardText,
  clipAssetBytes,
  bytesToBase64,
  base64ToBytes,
  pasteClipboard,
  duplicateNodes,
  tokensReferencedBy,
  type ClipboardPayload,
  type ClipNode,
  type ClipComponent,
  type ClipAsset,
  type PasteOptions,
  type PasteResult,
} from './clipboard.ts'
export {
  renderHtml,
  renderSubtreeHtml,
  cssPropertyName,
  cssDeclarationValue,
  formatCssNumber,
  type HtmlOptions,
} from './html.ts'
export { sanitizeSvgMarkup, standaloneSvgMarkup } from './svgSanitize.ts'
