/**
 * The Google Fonts catalog (`googleFonts.json`, regenerated by `scripts/google-fonts.mjs`) and
 * the pure parts of loading a family: the CSS2 API request, parsing its `@font-face` rules and
 * mapping font file URLs onto `baren-font://`. Shared by main (which downloads and caches the
 * files) and the renderer (picker, `get_font_family_info`); DOM- and Node-free.
 *
 * Every family a design uses is loaded from Google Fonts on every machine, so text renders with
 * the same files for every collaborator, whether or not the font is installed locally.
 */
import { fontUrlOf, type FontFaceSpec } from './fontUrls'
import catalog from './googleFonts.json'

export { FONT_SCHEME, fontFileSource, fontPathOf, fontUrlOf, type FontFaceSpec } from './fontUrls'

export type GoogleFontCategory = 'sans' | 'serif' | 'display' | 'hand' | 'mono'

/** `"100..900"` for a variable wght axis, else the static weights. */
type Weights = string | number[]

export interface GoogleFont {
  family: string
  category: GoogleFontCategory
  /** Weights of the upright styles: a range for variable fonts, else the static list. */
  weights: Weights
  /** Same for italics, or null when the family has none. */
  italic: Weights | null
}

type Entry = [string, GoogleFontCategory, Weights, Weights | 0]

let families: readonly GoogleFont[] | null = null
let byName: Map<string, GoogleFont> | null = null

/** Every family in the catalog, sorted by name. */
export function googleFonts(): readonly GoogleFont[] {
  if (families === null) {
    families = (catalog.families as unknown as Entry[]).map(
      ([family, category, weights, italic]) => ({
        family,
        category,
        weights,
        italic: italic === 0 ? null : italic,
      }),
    )
  }
  return families
}

/** The catalog entry for a family name (case-insensitive, quotes and spaces trimmed). */
export function findGoogleFont(name: string): GoogleFont | null {
  if (byName === null) byName = new Map(googleFonts().map((f) => [f.family.toLowerCase(), f]))
  return byName.get(cleanFamilyName(name).toLowerCase()) ?? null
}

/** `'Geist'` → `Geist`; `"Geist Mono" ` → `Geist Mono`. */
export function cleanFamilyName(name: string): string {
  return name
    .trim()
    .replace(/^['"]|['"]$/g, '')
    .trim()
}

/** The families of a CSS `font-family` list, in order ("Geist, 'Geist Mono', sans-serif"). */
export function familyList(value: string): string[] {
  return value
    .split(',')
    .map(cleanFamilyName)
    .filter((f) => f.length > 0)
}

/** The weights a catalog entry lists (a variable range expands to its hundreds). */
export function weightList(weights: Weights): number[] {
  if (Array.isArray(weights)) return weights
  const [min, max] = weights.split('..').map(Number) as [number, number]
  const out: number[] = []
  for (let w = Math.ceil(min / 100) * 100; w <= max; w += 100) out.push(w)
  return out
}

/** CSS2 API URL for every weight and style of a family. */
export function css2Url(font: GoogleFont): string {
  const name = encodeURIComponent(font.family).replace(/%20/g, '+')
  const spec = (w: Weights) => (Array.isArray(w) ? w : [w])
  const upright = Array.isArray(font.weights) ? font.weights : [font.weights]
  let axes = ''
  if (font.italic !== null) {
    const tuples = [...upright.map((w) => `0,${w}`), ...spec(font.italic).map((w) => `1,${w}`)]
    axes = `:ital,wght@${tuples.join(';')}`
  } else if (!(upright.length === 1 && upright[0] === 400)) {
    axes = upright.length > 0 ? `:wght@${upright.join(';')}` : ''
  }
  return `https://fonts.googleapis.com/css2?family=${name}${axes}&display=swap`
}

/** The `@font-face` rules of a CSS2 response (woff2 sources), mapped onto `baren-font://`. */
export function parseFontFaces(css: string): FontFaceSpec[] {
  const out: FontFaceSpec[] = []
  for (const [, body] of css.matchAll(/@font-face\s*\{([^}]*)\}/g)) {
    const prop = (name: string) =>
      new RegExp(`(?:^|;)\\s*${name}\\s*:\\s*([^;]+)`).exec(body ?? '')?.[1]?.trim()
    const src = /url\(\s*['"]?([^'")\s]+)['"]?\s*\)/.exec(prop('src') ?? '')?.[1]
    const url = src ? fontUrlOf(src) : null
    if (url === null) continue
    const style = prop('font-style') === 'italic' ? 'italic' : 'normal'
    const weight = prop('font-weight') ?? '400'
    if (!/^\d{1,4}(?: \d{1,4})?$/.test(weight)) continue
    const range = prop('unicode-range')
    const face: FontFaceSpec = { style, weight, url }
    if (range && /^[U+0-9A-Fa-f?,\s-]+$/.test(range)) face.unicodeRange = range
    out.push(face)
  }
  return out
}
