/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * The local persistence backend: design files (Loro documents), assets and
 * thumbnails in one SQLite database. Create one per process.
 */
export declare class CoreHandle {
  /**
   * `path` is the data directory (an existing directory; the database is
   * `<path>/baren.sqlite`) or the database file itself. The constructor
   * does not touch the disk: the database is opened (created and migrated
   * if needed) by the first call, on a worker thread, and open errors reject
   * that call. One handle owns a database at a time; another open rejects
   * with `[locked]` until `close()` resolves or the owning process exits.
   */
  constructor(path: string, options?: CoreOptions | undefined | null)
  /** Every file, most recently updated first (archived files included). */
  listFiles(): Promise<Array<FileMeta>>
  /** Create a file holding an empty document (one page, "Page 1"). */
  createFile(name: string): Promise<FileMeta>
  /**
   * Create a file from a Loro snapshot (e.g. fetched from the server).
   * `name` overrides the document's `meta.name`.
   */
  importFile(snapshot: Uint8Array, name?: string | undefined | null): Promise<FileMeta>
  /** Rename a file (also written into the document's `meta.name`). */
  renameFile(id: string, name: string): Promise<void>
  archiveFile(id: string, archived: boolean): Promise<void>
  /** Link a local file to a team file on the server (`null`s unlink). */
  setFileRemote(id: string, teamId?: string | undefined | null, remoteId?: string | undefined | null): Promise<void>
  /** Delete a file, its history and thumbnail (assets are shared and kept). */
  removeFile(id: string): Promise<void>
  /** The file's current Loro snapshot (load it with `loadDoc`). */
  openFile(id: string): Promise<Buffer>
  /**
   * Validate a Loro update (or snapshot) against the file's document and
   * append it durably. Updates may arrive out of order; ones that add
   * nothing new are ignored. Rejects with `[invalid-update]` otherwise.
   */
  applyUpdate(id: string, update: Uint8Array): Promise<void>
  /**
   * Fold the file's update log into a fresh snapshot now (e.g. when its
   * window closes). Happens automatically every 500 updates.
   */
  compactFile(id: string): Promise<void>
  /** Store the file's thumbnail (PNG bytes). */
  setThumbnail(id: string, png: Uint8Array): Promise<void>
  /** The file's thumbnail, or `null` when it has none. */
  getThumbnail(id: string): Promise<Buffer | null>
  /** Store a blob; resolves to its blake3 hex digest (deduplicated). */
  putAsset(bytes: Uint8Array, mime: string): Promise<string>
  /** The asset's bytes, or `null` when no asset has this hash. */
  getAsset(hash: string): Promise<Buffer | null>
  /**
   * The asset's bytes and stored mime type, or `null` (for serving
   * `baren-asset://<hash>` with the right `Content-Type`).
   */
  getAssetFile(hash: string): Promise<AssetFile | null>
  /**
   * Mime, byte size and pixel size (from the image header) of an asset, or
   * `null` when no asset has this hash.
   */
  getAssetInfo(hash: string): Promise<AssetInfo | null>
  /**
   * A node's subtree as semantic HTML with inline styles; tokens become
   * `:root` custom properties. Image layers and image fills are inlined as
   * `data:` URIs by default (clipboard export).
   */
  exportHtml(fileId: string, nodeId: string, options?: HtmlExportOptions | undefined | null): Promise<string>
  /**
   * The document as `DocSnapshot` JSON, printed like
   * `JSON.stringify(toSnapshot(doc), null, 2)`; with `embedAssets`, plus the
   * referenced assets as `data:` URIs under `assets`.
   */
  exportJson(fileId: string, options?: JsonExportOptions | undefined | null): Promise<string>
  /**
   * Compact open documents, checkpoint the database and release it. Call
   * on app quit; later calls reject with `[closed]`. Nothing is lost if
   * this is never called (every update is durable when its promise resolves).
   */
  close(): Promise<void>
}

/** An asset's bytes with its stored mime (what `baren-asset://` serves). */
export interface AssetFile {
  bytes: Buffer
  mime: string
}

/**
 * What `getAssetInfo` reports. `width`/`height` come from the image header
 * (no decoding) and are `null` for non-images.
 */
export interface AssetInfo {
  mime: string
  /** Byte size. */
  size: number
  width: number | null
  height: number | null
}

/** Optional tuning for `new CoreHandle(dbPath, options)`. Defaults suit the app. */
export interface CoreOptions {
  /**
   * Documents kept loaded in memory (least recently used are compacted
   * and dropped). Default 8.
   */
  cacheCapacity?: number
  /** Compact a file's update log after this many updates. Default 500. */
  compactEvery?: number
  /** …or after this many bytes of updates. Default 8 MiB. */
  compactBytes?: number
}

/** Version of the native core (for diagnostics / About dialog). */
export declare function coreVersion(): string

/** File metadata, as in the desktop bridge's `FileMeta`. */
export interface FileMeta {
  id: string
  name: string
  /** Milliseconds since the Unix epoch. */
  createdAt: number
  /** Milliseconds since the Unix epoch; bumped by edits, renames and archiving. */
  updatedAt: number
  archived: boolean
  teamId: string | null
  remoteId: string | null
}

/** Options for `exportHtml`. */
export interface HtmlExportOptions {
  /** A complete `<!doctype html>` document instead of a fragment. Default false. */
  document?: boolean
  /** Inline images as `data:` URIs. Default true. */
  embedAssets?: boolean
  /** Add `data-node-id` attributes. Default false. */
  includeNodeIds?: boolean
  /** `src` prefix for images that are not embedded. Default `"baren-asset://"`. */
  assetUrlPrefix?: string
}

/** Options for `exportJson`. */
export interface JsonExportOptions {
  /**
   * Add `assets: { <hash>: "data:<mime>;base64,…" }` for every referenced
   * asset (a self-contained copy). Default false.
   */
  embedAssets?: boolean
}
